WITH CTE AS (
SELECT 
TO_TIMESTAMP((STARTTIME)) as STARTED_AT,
DATE(TO_TIMESTAMP((STARTTIME))) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP((STARTTIME))) AS HOUR_STARTED_AT,
MONTH(TO_TIMESTAMP((STARTTIME))) AS MONTH,


{{day_name(('STARTTIME'))}} as DAY_TYPE,



-- CASE 
-- WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2) THEN 'WINTER'
-- WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,4,5) THEN 'SPRING'
-- WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8) THEN 'SUMMER'
-- ELSE 'AUTUMN'
-- END AS SEASON_OF_YEAR


-- Convert the above logic into a macro


{{get_season(('STARTTIME'))}} as SEASON_OF_YEAR


FROM 
{{ ref('stg_bike') }}
)
SELECT * 
FROM CTE




